#!/usr/bin/env bash
# You can call this script like this:
# $./volume up
# $./volume down
# $./volume mute

DIR="$HOME/.config/dunst"

function send_notification {
  bright=`brightnessctl get`
  bar=$($bright / 5)
  dunstify "Brightness $bright% " -r 5555 -u normal
}

case $1 in
  up)
    brightnessctl set 5%+
    send_notification
    ;;
  down)
    brightnessctl set 5%- 
    send_notification
    ;;
esac

