#!/bin/env bash

  
while true
do
    case "$1" in
    "up")
        hyprctl dispatch resizeactive 0 40
        hyprctl dispatch moveactive 0 -40
        exit 0
        ;;
    "left")
        hyprctl dispatch resizeactive 40 0
        hyprctl dispatch moveactive -40 0
        exit 0
        ;;
    esac
done
