format = " $directory $character"
palette = "catppuccin_mocha"
right_format = """$git_status $git_branch $cmd_duration"""
add_newline = false

# Other languages configurations:
rust.disabled = false
lua.disabled = false

# Prompt symbols 
[character]
success_symbol = "[](teal bold)"
error_symbol = "[](red)"
vicmd_symbol = "[](green)"

[directory]
format = "($style)[ ](bg:none fg:pink)[$path](bg:none fg:pink bold)($style)"
style = "bg:none fg:pink"
truncation_length = 3
truncate_to_repo = false

[git_branch]
format = "($style)[[ ](bg:none fg:pink bold)$branch](bg:none fg:pink)($style)"
style = "bg:none fg:base"

[git_status]
# $all status$ahead_behind
format = "($style)[$all_status$ahead_behind](bg:none fg:pink)($style)"
style = "bg:none fg:base"
conflicted = "="
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
up_to_date = ""
untracked = "?${count}"
stashed = ""
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "${count}"

[palettes.catppuccin_mocha]
base = "#1e1e2e"
blue = "#89b4fa"
crust = "#11111b"
flamingo = "#f2cdcd"
green = "#a6e3a1"
lavender = "#b4befe"
mantle = "#181825"
maroon = "#eba0ac"
mauve = "#cba6f7"
overlay0 = "#6c7086"
overlay1 = "#7f849c"
overlay2 = "#9399b2"
peach = "#fab387"
pink = "#f5c2e7"
red = "#f38ba8"
rosewater = "#f5e0dc"
sapphire = "#74c7ec"
sky = "#89dceb"
subtext0 = "#a6adc8"
subtext1 = "#bac2de"
surface0 = "#313244"
surface1 = "#45475a"
surface2 = "#585b70"
teal = "#94e2d5"
text = "#cdd6f4"
yellow = "#f9e2af"

[cmd_duration]
min_time = 1
# duration & style 
format = "($style)[(bg:none fg:pink bold)$duration](bg:none fg:pink)($style)"
disabled = false
style = "bg:none fg:base"
